# Generated by Django 4.2.2 on 2023-07-28 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('cedula', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LocalRepuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=30)),
                ('valor_total_mercaderia', models.FloatField()),
                ('valor_pago_permiso', models.FloatField()),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales.barrio')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales.persona')),
            ],
        ),
        migrations.CreateModel(
            name='LocalComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=30)),
                ('tipo_comida', models.CharField(max_length=30)),
                ('ventas_proyectadas_mes', models.FloatField()),
                ('pago_permiso', models.FloatField()),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barrio_Comida', to='locales.barrio')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietario_Comida', to='locales.persona')),
            ],
        ),
    ]
