# Generated by Django 4.2.3 on 2023-07-28 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localcomida',
            name='pago_permiso',
        ),
        migrations.RemoveField(
            model_name='localrepuestos',
            name='valor_pago_permiso',
        ),
    ]
